apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: order-mgmt-service
spec:
  selector:
    app: order-mgmt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: user-mgmt-service
spec:
  selector:
    app: user-mgmt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: cart-mgmt-service
spec:
  selector:
    app: cart-mgmt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000